export const canciones = [
    ["A", true],
    ["A mi palomita","amipalomita", false],
    ["Abanico español", "amipalomita", false],
    ["Acongójame", "amipalomita", false],
    ["Acurrúcame", "amipalomita", false],
    ["Adelita del Pozo", "amipalomita", false],
    ["Adiós a la llanera", "amipalomita", false],
    ["Adiós con el corazón", "amipalomita", false],
    ["Adios Granada", "amipalomita", false],
    ["Adoro", "amipalomita", false],
    ["Agáchate el sombrerito", "amipalomita", false],
    ["Agua del pozo", "amipalomita", false],
    ["Agua,azucarillos y aguardiente", "amipalomita", false],
    ["Ahora seremos felices", "amipalomita", false],
    ["Aires Andaluces", "amipalomita", false],
    ["Aires de Mayab", "amipalomita", false],
    ["Aires de Salamanca", "amipalomita", false],
    ["Aires de tuna (pasodobles)", "amipalomita", false],
    ["Aires del norte", "amipalomita", false],
    ["Aires sudamericanos", "amipalomita", false],
    ["Aires vascos", "amipalomita", false],
    ["Al clarear", "amipalomita", false],
    ["Alalá-Alborada", "amipalomita", false],
    ["Alcalá de Henares", "amipalomita", false],
    ["Alfonsina y el mar", "amipalomita", false],
    ["Alforja Campesina", "amipalomita", false],
    ["Algo contigo", "amipalomita", false],
    ["Alicantina", "amipalomita", false],
    ["Allí", "amipalomita", false],
    ["Alma de Dios", "amipalomita", false],
    ["Alma llanera", "amipalomita", false],
    ["Alma, corazón y vida", "amipalomita", false],
    ["Amalia", "amipalomita", false],
    ["Amalia Rosa", "amipalomita", false],
    ["Amapola", "amipalomita", false],
    ["Amarraditos", "amipalomita", false],
    ["Amelia", "amipalomita", false],
    ["Amémonos", "amipalomita", false],
    ["Amigo", "amipalomita", false],
    ["Amigo", "amipalomita", false],
    ["Amigos para siempre", "amipalomita", false],
    ["Amor canario", "amipalomita", false],
    ["Amor del alma", "amipalomita", false],
    ["Amor y Fiesta", "amipalomita", false],
    ["Amores", "amipalomita", false],
    ["Amoríos en el molino", "amipalomita", false],
    ["Amorosa Guajira", "amipalomita", false],
    ["Amparito Roca", "amipalomita", false],
    ["Anchieta", "amipalomita", false],
    ["Angelitos negros", "amipalomita", false],
    ["Ansiedad", "amipalomita", false],
    ["Añoranzas", "amipalomita", false],
    ["Aquella tarde", "amipalomita", false],
    ["Arrullo", "amipalomita", false],
    ["Así es Lima", "amipalomita", false],
    ["Así es mi Granada", "amipalomita", false],
    ["Asturianina", "amipalomita", false],
    ["Asturias", "amipalomita", false],
    ["Ave María no Morro", "amipalomita", false],
    ["Ay,ay,ay", "amipalomita", false],
    ["Ayer", "amipalomita", false],
    ["El andariego", "amipalomita", false],
    ["La Adelita", "amipalomita", false],
    ["La Aurora", "amipalomita", false],
    ["Los amores de Ana", "amipalomita", false],
    ["B", true],
    ["Baixant de la Font del Gat", "amipalomita", false],
    ["Barlovento", "amipalomita", false],
    ["Barrio brujo", "amipalomita", false],
    ["Basura", "amipalomita", false],
    ["Becas amarillas", "amipalomita", false],
    ["Bella enamorada", "amipalomita", false],
    ["Bello amanecer", "amipalomita", false],
    ["Bendita mi tierra guanche", "amipalomita", false],
    ["Bésame Morenita", "amipalomita", false],
    ["Bésame mucho", "amipalomita", false],
    ["Bolero a Murcia", "amipalomita", false],
    ["Boleros (varios autores)", "amipalomita", false],
    ["Boricua en la Luna/¿Qué es Patria?", "amipalomita", false],
    ["Bossa Nova", "amipalomita", false],
    ["El barbero de Sevilla", "amipalomita", false],
    ["El beso", "amipalomita", false],
    ["El borrachito", "amipalomita", false],
    ["La balada del marino", "amipalomita", false],
    ["La banda", "amipalomita", false],
    ["La barca", "amipalomita", false],
    ["La barca de oro", "amipalomita", false],
    ["La bella Lola", "amipalomita", false],
    ["La Bikina", "amipalomita", false],
    ["La bruja (jota)", "amipalomita", false],
    ["La leyenda del beso (intermedio)", "amipalomita", false],
    ["Un bolero de Madrid", "amipalomita", false],
    ["C", true],
    ["Al Clarear", "amipalomita", false],
    ["Café", "amipalomita", false],
    ["Callecita encendida", "amipalomita", false],
    ["Calles de León", "amipalomita", false],
    ["Calles sin rumbo", "amipalomita", false],
    ["Caminemos", "amipalomita", false],
    ["Camino del Santuario", "amipalomita", false],
    ["Canción de orfeo", "amipalomita", false],
    ["Canción del corazón", "amipalomita", false],
    ["Canción del Olvido,La", "amipalomita", false],
    ["Canción mixteca", "amipalomita", false],
    ["Candombe para José", "amipalomita", false],
    ["Canon", "amipalomita", false],
    ["Cántame un pasodoble español", "amipalomita", false],
    ["Cantinero de Cuba", "amipalomita", false],
    ["Canto a la espada", "amipalomita", false],
    ["Canto a Murcia", "amipalomita", false],
    ["Canto de carnaval", "amipalomita", false],
    ["Capriccio russo", "amipalomita", false],
    ["Carnaval del 98", "amipalomita", false],
    ["Carnavalito Humahuaqueño", "amipalomita", false],
    ["Carolina", "amipalomita", false],
    ["Carrascosa", "amipalomita", false],
    ["Celosa", "amipalomita", false],
    ["Cerca de ti", "amipalomita", false],
    ["Chapala", "amipalomita", false],
    ["Cielito lindo", "amipalomita", false],
    ["Cielo Andaluz", "amipalomita", false],
    ["Cinco letras", "amipalomita", false],
    ["Clavelitos", "amipalomita", false],
    ["Clavellina", "amipalomita", false],
    ["Cómo llora una estrella", "amipalomita", false],
    ["Con la mano...", "amipalomita", false],
    ["Contigo aprendí", "amipalomita", false],
    ["Contigo en la distancia", "amipalomita", false],
    ["Coplas de ronda", "amipalomita", false],
    ["Coplas Murcianas", "amipalomita", false],
    ["Corazón", "amipalomita", false],
    ["Corazón Espinado", "amipalomita", false],
    ["Cordobesita", "amipalomita", false],
    ["Coro de los repatriados", "amipalomita", false],
    ["Cuando escuches un rumor", "amipalomita", false],
    ["Cuando salí de Cuba", "amipalomita", false],
    ["Cuando te encuentres sola (Amar)", "amipalomita", false],
    ["Cucurrucucú, Paloma", "amipalomita", false],
    ["Cumbres del Teide", "amipalomita", false],
    ["Dos cruces", "amipalomita", false],
    ["El canastillo de fresas", "amipalomita", false],
    ["El chotis del feo", "amipalomita", false],
    ["La caja de música", "amipalomita", false],
    ["La copla del rondador", "amipalomita", false],
    ["La czarda de Monti", "amipalomita", false],
    ["Las cintas de mi capa", "amipalomita", false],
    ["Las colombianas", "amipalomita", false],
    ["Los colorines", "amipalomita", false],
    ["D", true],
    ["Dama de España", "amipalomita", false],
    ["Danza del fuego", "amipalomita", false],
    ["Danza Húngara", "amipalomita", false],
    ["De colores", "amipalomita", false],
    ["Debajo de tu balcón", "amipalomita", false],
    ["Derroche", "amipalomita", false],
    ["Descarga de son cubano", "amipalomita", false],
    ["Despierta", "amipalomita", false],
    ["Despierta niña", "amipalomita", false],
    ["Desvelo de amor", "amipalomita", false],
    ["Dime que sí", "amipalomita", false],
    ["Doble águila", "amipalomita", false],
    ["Don gil de Alcala (Elegia al vino de Jerez)", "amipalomita", false],
    ["Don Manolito. Viva Madrid", "amipalomita", false],
    ["Doña Francisquita. Pasacalles de los estudiantes", "amipalomita", false],
    ["Dos gardenias", "amipalomita", false],
    ["Dos palomitas", "amipalomita", false],
    ["Dos puntas", "amipalomita", false],
    ["Dr. Zhivago", "amipalomita", false],
    ["Dulce Sonar", "amipalomita", false],
    ["El día que me quieras", "amipalomita", false],
    ["El diablo suelto", "amipalomita", false],
    ["La Donna e Mobile", "amipalomita", false],
    ["Lo dudo", "amipalomita", false],
    ["E", true],
    ["Ecos de Haren", "amipalomita", false],
    ["Ecos de ronda", "amipalomita", false],
    ["El Baile de Luis Alonso", "amipalomita", false],
    ["Él estudiaba para ingeniero", "amipalomita", false],
    ["El paso", "amipalomita", false],
    ["Ella", "amipalomita", false],
    ["Elsa", "amipalomita", false],
    ["En mi viejo San Juan", "amipalomita", false],
    ["En noche lóbrega", "amipalomita", false],
    ["En tierra extraña", "amipalomita", false],
    ["Enamorada", "amipalomita", false],
    ["Endecha", "amipalomita", false],
    ["Entre la tierra y el cielo", "amipalomita", false],
    ["Envidia", "amipalomita", false],
    ["España cañí", "amipalomita", false],
    ["Española", "amipalomita", false],
    ["Españolita", "amipalomita", false],
    ["Esta noche no alumbra…", "amipalomita", false],
    ["Esta tarde vi llover", "amipalomita", false],
    ["Esta tarde, es mía / Novillero", "amipalomita", false],
    ["Estampa cumanesa", "amipalomita", false],
    ["Estoy perdido", "amipalomita", false],
    ["Estrella de la Noche", "amipalomita", false],
    ["Estrellita del sur", "amipalomita", false],
    ["Estudiantina andaluza", "amipalomita", false],
    ["Estudiantina del corazón", "amipalomita", false],
    ["Estudiantina en tu reja", "amipalomita", false],
    ["Estudiantina madrileña", "amipalomita", false],
    ["Estudiantina portuguesa", "amipalomita", false],
    ["Euskal Herriko", "amipalomita", false],
    ["La espinita", "amipalomita", false],
    ["F", true],
    ["El Fallero", "amipalomita", false],
    ["Fina Estampa", "amipalomita", false],
    ["Flor de Ausencia", "amipalomita", false],
    ["Flor de azalea", "amipalomita", false],
    ["Flor marchita", "amipalomita", false],
    ["Flor marina", "amipalomita", false],
    ["Folia Canaria", "amipalomita", false],
    ["Folías parranderas", "amipalomita", false],
    ["Fonseca", "amipalomita", false],
    ["Francisco alegre", "amipalomita", false],
    ["Frenesí", "amipalomita", false],
    ["Funiculí", "amipalomita", false],
    ["La feria", "amipalomita", false],
    ["La fiesta de San Benito", "amipalomita", false],
    ["La flor de la canela", "amipalomita", false], 
    ["G", true],
    ["El gitano señorón", "amipalomita", false],
    ["Gallito", "amipalomita", false],
    ["Gallito Camarón", "amipalomita", false],
    ["Gallito de la pasión", "amipalomita", false],
    ["Galopera", "amipalomita", false],
    ["Gaudeamus Igitur", "amipalomita", false],
    ["Gibraltareña", "amipalomita", false],
    ["Gigantes y Cabezudos", "amipalomita", false],
    ["Golondrina viajera", "amipalomita", false],
    ["Granada", "amipalomita", false],
    ["Granada (instrumental)", "amipalomita", false],
    ["Guadalajara", "amipalomita", false],
    ["Guantanamera", "amipalomita", false],
    ["La Giralda", "amipalomita", false],
    ["La golondrina", "amipalomita", false],
    ["La gracia de Dios", "amipalomita", false],
    ["H", "amipalomita", false],
    ["Habanera de Cádiz", "amipalomita", false],
    ["Habanera de Cuba", "amipalomita", false],
    ["Hace un año", "amipalomita", false],
    ["Hay algo que no te dé", "amipalomita", false],
    ["Hechizo borinqueño", "amipalomita", false],
    ["Hongaarse Dans nº5", "amipalomita", false],
    ["Horas de ronda", "amipalomita", false],
    ["Hoy estoy aquí", "amipalomita", false],
    ["La hiedra", "amipalomita", false],
    ["Las hojas muertas", "amipalomita", false],
    ["I", "amipalomita", false],
    ["Idilio", "amipalomita", false],
    ["Imágenes de ayer", "amipalomita", false],
    ["Impromptu (en vivo)", "amipalomita", false],
    ["Isa de Ronda", "amipalomita", false],
    ["Isa del candidito", "amipalomita", false],
    ["Isa parrandera", "amipalomita", false],
    ["Islas Canarias", "amipalomita", false],
    ["J", "amipalomita", false],
    ["Jacarandosa", "amipalomita", false],
    ["Jalisco", "amipalomita", false],
    ["Jamás, Jamás", "amipalomita", false],
    ["Jota del estudiante (La Linda Tapada)", "amipalomita", false],
    ["Jota parrandera", "amipalomita", false],
    ["Jotas Navarras", "amipalomita", false],
    ["Júrame", "amipalomita", false],
    ["La jota de la Dolores", "amipalomita", false],
    ["L", "amipalomita", false],
    ["La boda de Luis Alonso", "amipalomita", false],
    ["La Dolores", "amipalomita", false],
    ["La Laguna (canción canaria)", "amipalomita", false],
    ["La ley del barrio", "amipalomita", false],
    ["La llamadora", "amipalomita", false],
    ["La mulata y el pirata", "amipalomita", false],
    ["Lágrimas negras", "amipalomita", false],
    ["Lamento Borincano", "amipalomita", false],
    ["Lejos del Mar", "amipalomita", false],
    ["Lela", "amipalomita", false],
    ["Letras de ronda", "amipalomita", false],
    ["Lía", "amipalomita", false],
    ["Limeña", "amipalomita", false],
    ["Lisboa antigua", "amipalomita", false],
    ["Llévatela", "amipalomita", false],
    ["Llorarán las estrellas", "amipalomita", false],
    ["Loca Pasión", "amipalomita", false],
    ["Lodo (Si tu me dices ven...)", "amipalomita", false],
    ["Luna de Arrabal", "amipalomita", false],
    ["Luna de España", "amipalomita", false],
    ["M", "amipalomita", false],
    ["El Manisero", "amipalomita", false],
    ["El Manolo", "amipalomita", false],
    ["El menjurgue", "amipalomita", false],
    ["El menú", "amipalomita", false],
    ["El mirador", "amipalomita", false],
    ["El muerto vivo", "amipalomita", false],
    ["La madrugada", "amipalomita", false],
    ["La Marcha Turca", "amipalomita", false],
    ["La Mari Pepa (Clavelitos Madrileños)", "amipalomita", false],
    ["La marimba", "amipalomita", false],
    ["La media vuelta", "amipalomita", false],
    ["La melitona", "amipalomita", false],
    ["La mentira (Se te olvida)", "amipalomita", false],
    ["La mitad", "amipalomita", false],
    ["La morena de mi copla", "amipalomita", false],
    ["La mujer que yo quiero", "amipalomita", false],
    ["La muralla", "amipalomita", false],
    ["Las mañanitas del rey David", "amipalomita", false],
    ["Madrid", "amipalomita", false],
    ["Madrigal", "amipalomita", false],
    ["Madrina", "amipalomita", false],
    ["Magdalena", "amipalomita", false],
    ["Maite", "amipalomita", false],
    ["Maitechu mia", "amipalomita", false],
    ["Mala persona", "amipalomita", false],
    ["Málaga", "amipalomita", false],
    ["Málaga Reina Calé", "amipalomita", false],
    ["Malagueña", "amipalomita", false],
    ["Malagueñas de Sal, Retama y Llano/A Venezuela", "amipalomita", false],
    ["Mamen", "amipalomita", false],
    ["Manoliño", "amipalomita", false],
    ["Mañana de carnaval", "amipalomita", false],
    ["Mar azul", "amipalomita", false],
    ["Mar y cielo", "amipalomita", false],
    ["Maracaibo", "amipalomita", false],
    ["María", "amipalomita", false],
    ["María Cervantes", "amipalomita", false],
    ["María Chuchena", "amipalomita", false],
    ["María Dolores", "amipalomita", false],
    ["María La Portuguesa", "amipalomita", false],
    ["María va", "amipalomita", false],
    ["Maribel", "amipalomita", false],
    ["Marinero", "amipalomita", false],
    ["Mariposa", "amipalomita", false],
    ["Mattinata", "amipalomita", false],
    ["Mazurca del Rey", "amipalomita", false],
    ["Medicina tuna mix", "amipalomita", false],
    ["Medley Español", "amipalomita", false],
    ["Memorias de una vieja canción", "amipalomita", false],
    ["Menina estás a Janela", "amipalomita", false],
    ["Mi Jaragual/Te quiero ver/Mamita llegó el Obispo", "amipalomita", false],
    ["Mi propuesta", "amipalomita", false],
    ["Mía", "amipalomita", false],
    ["Mira que eres linda", "amipalomita", false],
    ["Mis noches sin ti", "amipalomita", false],
    ["Moliendo café", "amipalomita", false],
    ["Morenita mía", "amipalomita", false],
    ["Morucha", "amipalomita", false],
    ["Motivos", "amipalomita", false],
    ["Muchachita sabanera", "amipalomita", false],
    ["Mujer", "amipalomita", false],
    ["Mujer leonesa", "amipalomita", false],
    ["Mujer Mediterránea", "amipalomita", false],
    ["Mujer te canta Distrito", "amipalomita", false],
    ["Muñequita linda"],    
    ["N", "amipalomita", false],
    ["Naranjitai", "amipalomita", false],
    ["Nave del olvido, La", "amipalomita", false],
    ["Nessum Dorma", "amipalomita", false],
    ["Niña divina", "amipalomita", false],
    ["Niños del Pireo, Los", "amipalomita", false],
    ["No me quieras tanto", "amipalomita", false],
    ["No se por qué te quiero", "amipalomita", false],
    ["No vull que plores més", "amipalomita", false],
    ["Noche de ronda", "amipalomita", false],
    ["Noche hermosa", "amipalomita", false],
    ["Noche lóbrega", "amipalomita", false],
    ["Noche perfumada", "amipalomita", false],
    ["Noche plateada", "amipalomita", false],
    ["Noches de Cartagena", "amipalomita", false],
    ["Noches de leyenda/Murcia", "amipalomita", false],
    ["Nostalgias", "amipalomita", false],
    ["Nube gris", "amipalomita", false],
    ["O", "amipalomita", false],
    ["Los ojos de mi Charra", "amipalomita", false],
    ["O sole mio", "amipalomita", false],
    ["Obsesión", "amipalomita", false],
    ["Oh Mary", "amipalomita", false],
    ["Ojos de España", "amipalomita", false],
    ["Orgullosamente mujer", "amipalomita", false],
    ["Oye como va", "amipalomita", false],
    ["P", "amipalomita", false],
    ["A Paraguay", "amipalomita", false],
    ["El parao", "amipalomita", false],
    ["El parrandero", "amipalomita", false],
    ["P'a todo el año", "amipalomita", false],
    ["Pájaro Campana/Pájaro Chogüí", "amipalomita", false],
    ["Pájaro Cantor", "amipalomita", false],
    ["Pájaro Chogüi", "amipalomita", false],
    ["Palmeras, Las", "amipalomita", false],
    ["Palmero (Katay-katay)", "amipalomita", false],
    ["Paloma mensajera", "amipalomita", false],
    ["Paloma, La", "amipalomita", false],
    ["Panderetas y violines", "amipalomita", false],
    ["Paraná", "amipalomita", false],
    ["Párate", "amipalomita", false],
    ["Parquecito, El", "amipalomita", false],
    ["Pasacalles de Las Coquetas", "amipalomita", false],
    ["Pasacorbatas", "amipalomita", false],
    ["Pasacorridos", "amipalomita", false],
    ["Paso alegre", "amipalomita", false],
    ["Patria querida (waltz)", "amipalomita", false],
    ["Patria querida (pasodoble)", "amipalomita", false],
    ["El payaso del Raval", "amipalomita", false],
    ["Pepe Botella", "amipalomita", false],
    ["Perfume de gardenias", "amipalomita", false],
    ["Perla", "amipalomita", false],
    ["Perla fina", "amipalomita", false],
    ["La petenera", "amipalomita", false],
    ["Pídemelo todo", "amipalomita", false],
    ["Piensa en mi", "amipalomita", false],
    ["Plegaria", "amipalomita", false],
    ["Por amor", "amipalomita", false],
    ["Por el amor de una mujer", "amipalomita", false],
    ["Por la calle de Alcalá", "amipalomita", false],
    ["Por la vuelta de la sierra", "amipalomita", false],
    ["Por las penas", "amipalomita", false],
    ["Por qué no me besas", "amipalomita", false],
    ["Preludio", "amipalomita", false],
    ["Preludio corto", "amipalomita", false],
    ["Preludio en Sol menor", "amipalomita", false],
    ["Preludio y adagio", "amipalomita", false],
    ["Presentimiento", "amipalomita", false],
    ["Promesa", "amipalomita", false],
    ["Pueblos de España", "amipalomita", false],
    ["Pueblo's canción", "amipalomita", false],
    ["Que bonita es mi niña", "amipalomita", false],
    ["Qué bonita es mi tierra", "amipalomita", false],
    ["Qué será de ti", "amipalomita", false],
    ["Que te parece (Chaparra de mi amor)", "amipalomita", false],
    ["Quiereme", "amipalomita", false],
    ["Quiero", "amipalomita", false],
    ["Rancho grande", "amipalomita", false],
    ["Recuerdos de la Alhambra", "amipalomita", false],
    ["Red roses for a blue lady", "amipalomita", false],
    ["Reina de corazones", "amipalomita", false],
    ["Reina de las flores", "amipalomita", false],
    ["Renacer de Cádiz", "amipalomita", false],
    ["Renunciacíón (Negra, no te vaiga)", "amipalomita", false],
    ["Requiem", "amipalomita", false],
    ["Retales de amor", "amipalomita", false],
    ["Retalitos", "amipalomita", false],
    ["Rey de reyes", "amipalomita", false],
    ["Río Manzanares", "amipalomita", false],
    ["Ritmo africano", "amipalomita", false],
    ["Robleda", "amipalomita", false],
    ["Ronda del amanecer", "amipalomita", false],
    ["Ronda peregrina", "amipalomita", false],
    ["Rosario de rosa", "amipalomita", false],
    ["Rosita", "amipalomita", false],
    ["Rosita Moni Monita", "amipalomita", false],
    ["Rosita Morin", "amipalomita", false],
    ["El Rossegón", "amipalomita", false],
    ["La rosa y el jazmín", "amipalomita", false],
    ["Las rosas", "amipalomita", false],
    ["Rosas a Montmartre", "amipalomita", false],
    ["Rosas para una diva", "amipalomita", false],
    ["Las rosas rojas", "amipalomita", false],
    ["Rosita", "amipalomita", false],
    ["Rosita Monterito", "amipalomita", false],
    ["La revoltosa (Selección)", "amipalomita", false],
    ["Sabor a mí", "amipalomita", false],
    ["Salta Violeta", "amipalomita", false],
    ["El saludo", "amipalomita", false],
    ["La sardana de Montserrat", "amipalomita", false],
    ["Sarandonga", "amipalomita", false],
    ["Se nos rompió el amores", "amipalomita", false],
    ["Se va el caimán", "amipalomita", false],
    ["Sebastiana", "amipalomita", false],
    ["Serranilla", "amipalomita", false],
    ["Serrezuela", "amipalomita", false],
    ["Si me amaras", "amipalomita", false],
    ["Si no fuera por ti", "amipalomita", false],
    ["Sicilia", "amipalomita", false],
    ["Siempre en mi corazón", "amipalomita", false],
    ["Siempre en mi corazón", "amipalomita", false],
    ["Sin otra igual", "amipalomita", false],
    ["Sin otro igual", "amipalomita", false],
    ["Solamente una vez", "amipalomita", false],
    ["Solitario, El", "amipalomita", false],
    ["Son de la loma", "amipalomita", false],
    ["Sonrie", "amipalomita", false],
    ["Sueño de amor", "amipalomita", false],
    ["Sueltame en la penumbra", "amipalomita", false],
    ["Suspiros de España", "amipalomita", false],
    ["Taconeo Gitano", "amipalomita", false],
    ["Taconeo Gitano (instrumental)", "amipalomita", false],
    ["Tangos de Almería", "amipalomita", false],
    ["Tangos de Granada", "amipalomita", false],
    ["Te prometo amor", "amipalomita", false],
    ["Te quiero", "amipalomita", false],
    ["Temblando", "amipalomita", false],
    ["Temblando (waltz)", "amipalomita", false],
    ["Tequila", "amipalomita", false],
    ["Teresa", "amipalomita", false],
    ["Tercio de quites (Verde y oro)", "amipalomita", false],
    ["Tiempos del amor", "amipalomita", false],
    ["Tiempos viejos", "amipalomita", false],
    ["Toda una vida", "amipalomita", false],
    ["Todo es bello", "amipalomita", false],
    ["Torbellino", "amipalomita", false],
    ["Torero", "amipalomita", false],
    ["Toro de la Vega", "amipalomita", false],
    ["Toro Guapo", "amipalomita", false],
    ["Tota pulchra", "amipalomita", false],
    ["Toto, Amor", "amipalomita", false],
    ["Toto, Toto", "amipalomita", false],
    ["Tres apasionadas", "amipalomita", false],
    ["Tu flor", "amipalomita", false],
    ["Tu que puedes, vuélvete", "amipalomita", false],
    ["Un ramito de violetas", "amipalomita", false],
    ["Vamos a dejarlo todo", "amipalomita", false],
    ["Vamos a la feria", "amipalomita", false],
    ["Vas a ver", "amipalomita", false],
    ["Vaya con dios", "amipalomita", false],
    ["Veracruz", "amipalomita", false],
    ["Vestida de grana y oro", "amipalomita", false],
    ["Vete de mi", "amipalomita", false],
    ["Viejas melodías", "amipalomita", false],
    ["Viene clareando", "amipalomita", false],
    ["Viva Murcia", "amipalomita", false],
    ["Viva Sevilla", "amipalomita", false],
    ["Volando", "amipalomita", false],
    ["Volver", "amipalomita", false],
    ["Y sin embargo te quiero", "amipalomita", false],
    ["Y sin embargo, te quiero (Canción de bodas)", "amipalomita", false],
    ["Ya es muy tarde", "amipalomita", false],
    ["Ya no me duele", "amipalomita", false],
    ["Yo me enamoré", "amipalomita", false],
    ["Yo quiero un burro", "amipalomita", false],
    ["Z", "amipalomita", false],
    ["Zaragoza", "amipalomita", false],
    ["El Zagalejo", "amipalomita", false],
  ];
  
  